#这是手动触发的基本工作流程

名字: 名称:手动工作流程

#控制操作何时运行。当使用用户界面手动触发时，工作流运行
#或者API。
在:
工作流_调度:
#工作流接受的输入工作流接受的输入。
输入:
名字:
#在用户界面中显示友好的描述,而不是"名称" #在用户界面中显示友好的描述，而不是“名称”
描述: '要问候的人'
#如果没有明确提供值,则为默认值#如果没有明确提供值，则为默认值
系统默认值: 世界
#必须提供输入,工作流才能运行#必须提供输入，工作流才能运行
需要: 真实的
#输入的数据类型#输入的数据类型
类型: 类型:字符串

#工作流运行由一个或多个可以顺序或并行运行的作业组成
工作:
#此工作流包含一个名为"问候"的作业#此工作流包含一个名为“问候”的作业
迎接:
#将运行作业的运行程序的类型#将运行作业的运行程序的类型
连续运行: 运行:Ubuntu-最新版

#步骤表示将作为作业的一部分执行的一系列任务#步骤表示将作为作业的一部分执行的一系列任务
步伐:
#使用转轮外壳运行单个命令#使用runners shell运行单个命令
    - 名字: -名称:发送问候
      run: run: echo "Hello ${{ inputs.name }} ""你好${{ inputs.name }} "
